# Generated by Django 4.2.3 on 2023-07-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_change_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagen',
            new_name='image',
        ),
    ]
