# Generated by Django 4.2.3 on 2023-08-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_change_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discounted_price',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='brand',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
